Add field printer_identifier + generate label url with post shipments…
myparcelnl/api pull request #67
Opened 2020-02-06 15:04 UTC by reindert-vetter

2020-02-06 15:06 UTC, EdieLemoine commented on index.html
> +                    <td>[a-z]*</td>
kan ook 0 karakters zijn?

2020-02-06 15:20 UTC, adem-demir approved these changes

2020-02-06 20:25 UTC, reindert-vetter commented on index.html
> +                    <td>[a-z]*</td>
Wow, inderdaad. Goed gezien!

2020-02-07 07:51 UTC, RichardPerdaan requested changes

2020-02-07 07:51 UTC, RichardPerdaan commented on index.html
> +          "pdf": "http://jos.api.staging.myparcel.nl/pdfs/f569bc5a247fcec09d6a8cba16ff7629ca8062f3"
```suggestion
          "pdf": "https://api.myparcel.nl/pdfs/f569bc5a247fcec09d6a8cba16ff7629ca8062f3"

```

2020-02-07 07:51 UTC, RichardPerdaan commented on index.html
> +    "pdf": "http://jos.api.staging.myparcel.nl/pdfs/f569bc5a247fcec09d6a8cba16ff7629ca8062f3"
```suggestion
    "pdf": "https://api.myparcel.nl/pdfs/f569bc5a247fcec09d6a8cba16ff7629ca8062f3"

```

2020-02-07 07:53 UTC, RichardPerdaan approved these changes

2020-02-07 07:54 UTC, merged