Change manual folder structure
myparcelnl/api pull request #69
Opened 2020-02-17 08:08 UTC by RichardPerdaan

2020-02-17 15:11 UTC, reindert-vetter requested changes

2020-02-17 15:11 UTC, reindert-vetter commented on index.html
> +      postman_buttons[i].setAttribute('data-postman-param', 'env%5BMyParcel%20public%5D=W3siZW5hYmxlZCI6dHJ1ZSwia2V5IjoiYXBpX2tleSIsInZhbHVlIjoiIn0seyJrZXkiOiJVc2VyLUFnZW50IiwidmFsdWUiOiJ7e1VzZXItQWd
Postman heeft niet de nieuwe delivery options endpoint

2020-02-17 15:11 UTC, reindert-vetter commented on index.html
> +      postman_buttons[i].setAttribute('data-postman-param', 'env%5BMyParcel%20public%5D=W3siZW5hYmxlZCI6dHJ1ZSwia2V5IjoiYXBpX2tleSIsInZhbHVlIjoiIn0seyJrZXkiOiJVc2VyLUFnZW50IiwidmFsdWUiOiJ7e1VzZXItQWd
en pickup location endpoint

2020-02-17 15:11 UTC, reindert-vetter commented on index.html
> +                                <li>belgie</li>
Geen flespakket?

2020-02-17 15:11 UTC, reindert-vetter commented on index.html
> +                    This section extends the <a href="#6_C">base functionaltity</a>.
```suggestion
                    This section extends the <a href="#6_C">base functionality</a>.

```
Toch?

2020-02-17 15:11 UTC, reindert-vetter commented on index.html
> +GET https://api.myparcel.nl/delivery_options/?platform=myparcel&carrier=postnl&cc=nl&number=66&postal_code=2132WT&cutoff_time=16:00:00&dropoff_days=1;2;3;4;5;6&monday_delivery=1&dropoff_delay=0&deliv
```suggestion
GET https://api.myparcel.nl/delivery_options?platform=myparcel&carrier=postnl&cc=nl&number=66&postal_code=2132WT&cutoff_time=16:00:00&dropoff_days=1;2;3;4;5;6&monday_delivery=1&dropoff_delay=0&deliverydays_window=2&exclude_delivery_type=1   HTTP/1.1

```
Waarom met een `/`? Werkt het anders niet?

2020-02-17 15:11 UTC, reindert-vetter commented on index.html
> +GET https://api.myparcel.nl/pickup_locations/?platform=myparcel&carrier=postnl&cc=be&carrier=1&number=49&postal_code=1000  HTTP/1.1
waarom met een `/`?
```suggestion
GET https://api.myparcel.nl/pickup_locations?platform=myparcel&carrier=postnl&cc=be&carrier=1&number=49&postal_code=1000  HTTP/1.1

```
Zie ook andere plekken

2020-02-17 15:23 UTC, RichardPerdaan commented on index.html
> +GET https://api.myparcel.nl/delivery_options/?platform=myparcel&carrier=postnl&cc=nl&number=66&postal_code=2132WT&cutoff_time=16:00:00&dropoff_days=1;2;3;4;5;6&monday_delivery=1&dropoff_delay=0&deliv
Het werkt allebei

2020-02-17 15:25 UTC, RichardPerdaan commented on index.html
> +GET https://api.myparcel.nl/pickup_locations/?platform=myparcel&carrier=postnl&cc=be&carrier=1&number=49&postal_code=1000  HTTP/1.1
Done

2020-02-17 15:41 UTC, RichardPerdaan commented on index.html
> +                                <li>belgie</li>
Done

2020-02-18 12:30 UTC, RichardPerdaan commented on index.html
> +      postman_buttons[i].setAttribute('data-postman-param', 'env%5BMyParcel%20public%5D=W3siZW5hYmxlZCI6dHJ1ZSwia2V5IjoiYXBpX2tleSIsInZhbHVlIjoiIn0seyJrZXkiOiJVc2VyLUFnZW50IiwidmFsdWUiOiJ7e1VzZXItQWd
Done

2020-02-18 12:31 UTC, reindert-vetter approved these changes

2020-02-18 12:37 UTC, reindert-vetter approved these changes

2020-02-18 13:19 UTC, merged