MY-23238 use Accept: application/vnd.shipment_label_link+json to hand…
myparcelnl/api pull request #77
Opened 2020-10-01 14:44 UTC by reindert-vetter

…le multiple labels

2020-10-01 14:50 UTC, EdieLemoine requested changes

2020-10-01 14:50 UTC, EdieLemoine commented on index.html
> +                  You will receive a url to a label, but the label is not immediately available and will return a http status of 404 until it is ready. Depending on the number of labels, this process
URL, HTTP

2020-10-01 14:50 UTC, EdieLemoine commented on index.html
> +
entertje

2020-10-02 07:06 UTC, reindert-vetter commented on index.html
> +                  You will receive a url to a label, but the label is not immediately available and will return a http status of 404 until it is ready. Depending on the number of labels, this process
done

2020-10-02 07:07 UTC, reindert-vetter commented on index.html
> +
done

2020-10-13 13:19 UTC, RichardPerdaan approved these changes

2020-10-13 13:21 UTC, merged